export const BUY_CAKE='BUY_CAKE';
export const FETCH_USER='FETCH_USER';
export const FETCH_USER_FAILURE='FETCH_USER_FAILURE';
export const REGISTER_USER='REGISTER_USER';
export const LOGIN_USER='LOGIN_USER';